%% ============================================
%% EMQX ACL – NL SCADA Center v1.0
%% ============================================

%% Core service
{allow, {username, "core-service"}, subscribe, ["site/+/device/+/data", "site/+/device/+/heartbeat", "site/+/device/+/event"]}.
{allow, {username, "core-service"}, publish, ["site/+/device/+/cmd", "site/+/config"]}.

%% Gateway (simulator)
{allow, {username, "gateway-sim"}, publish, ["site/+/device/+/data", "site/+/device/+/heartbeat", "site/+/device/+/event"]}.
{allow, {username, "gateway-sim"}, subscribe, ["site/+/device/+/cmd", "site/+/config"]}.

%% Mặc định từ chối tất cả
{deny, all, subscribe, ["#"]}.
{deny, all, publish, ["#"]}.