%%--------------------------------------------------------------------
%% EMQX Authorization Rules cho NL SCADA Center v1.0
%%--------------------------------------------------------------------

%% Rule dành cho user "core-service"
{allow, {username, "core-service"}, subscribe, ["tenant/+/device/+/data", "tenant/+/device/+/heartbeat"]}.
{allow, {username, "core-service"}, publish, ["data/#", "metadata/#"]}.

%% Rule dành cho user "gateway-sim" (mô phỏng Gateway)
{allow, {username, "gateway-sim"}, publish, ["tenant/+/device/+/data", "tenant/+/device/+/heartbeat"]}.
{allow, {username, "gateway-sim"}, subscribe, ["tenant/+/device/+/cmd"]}.

%% Mặc định: từ chối tất cả các user/topic khác
{deny, all, subscribe, ["#"]}.
{deny, all, publish, ["#"]}.